# Generated by Django 3.2.6 on 2021-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='contacts',
            field=models.CharField(default=996, max_length=12),
        ),
    ]
