# Generated by Django 3.2.6 on 2021-08-18 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_contacts_hostel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLikeFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'bad'), (2, 'not bad'), (3, 'ok'), (4, 'good'), (5, 'very good')], null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.hostel')),
            ],
        ),
        migrations.DeleteModel(
            name='AddRating',
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='hostel',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
