# Generated by Django 3.2.6 on 2021-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('bad', 1), ('not bad', 2), ('ok', 3), ('good', 4), ('very good', 5)]),
        ),
    ]
