# Generated by Django 3.2.6 on 2021-08-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rating_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating']},
        ),
    ]
